language: node_js

node_js:
  - "12"
  - "11"
  - "10"
  - "9"
  - "8"

stages:
  - Install
  - Tests
  - Builds

jobs:
  include:
    - stage: Install
      name: Package install
      script:
        - npm install

    - stage: Tests
      name: Unit Test
      script:
        - npm run lint
        - npm run test:type
        - npm run test

    - stage: Builds
      script:
        - npm run build

notifications:
  email:
    - shun10116@gmail.com
  slack:
    rooms:
      - hi-cordworkspace:EC6Q4SIRTddzUEE0rMDXrSl6#dev-travis
