name: Stage Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x, 18.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm install
        env:
          SEOLHUN_GITHUB_TOKEN: ${{secrets.SEOLHUN_GITHUB_TOKEN}}

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test --coverage

      - name: Build
        run: npm run build
        env:
          NODE_ENV: production

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: dev-travis
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
